# Generated by Django 4.2.3 on 2023-07-22 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_appointment_service_alter_appointment_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
